version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/todo_db

  streamlit:
    build: .
    command: streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./app:/app/app
    ports:
      - "8501:8501"
    depends_on:
      - web

volumes:
  db_data: 