version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"  # REST API
      - "50051:50051"  # gRPC
    volumes:
      - ./server:/app/server
      - ./proto:/app/proto
      - ./generated:/app/generated
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/app/client
      - ./proto:/app/proto
      - ./generated:/app/generated
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8000
      - GRPC_SERVER_PORT=50051
    depends_on:
      server:
        condition: service_healthy